//! Checks that hold `README.md` to the repository it describes.
//!
//! The README carries a table of line counts, a file count, the size of the
//! playground crate, and a badge with the number of tests. Every one of those is
//! a fact about the tree, and every one was maintained by hand.
//!
//! They drifted on six consecutive branches. Each time the correction was
//! mechanical, each time it was spotted only because somebody went looking, and
//! twice a per-row figure stayed wrong while the total beside it was updated,
//! which is how a row comes to look maintained because its neighbour is.
//!
//! A number nobody checks is a number that is wrong at some point and stays
//! wrong until a reader notices. This is the same discipline
//! `tests/specification.rs` applies to the builtin list, applied to the other
//! set of hand-kept numbers in the project.
//!
//! **When one of these fails, the README is out of date, not the test.** The
//! message says which figure and what it should be.

use std::fs;
use std::path::{Path, PathBuf};

fn root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn readme() -> String {
    fs::read_to_string(root().join("README.md")).expect("the README is in the repository")
}

/// Count lines the way a reader would: one per line of text.
fn lines_in(path: &Path) -> usize {
    fs::read_to_string(path)
        .unwrap_or_else(|err| panic!("cannot read {}: {err}", path.display()))
        .lines()
        .count()
}

fn lines_of(dir: &str, names: &[&str]) -> usize {
    names
        .iter()
        .map(|name| lines_in(&root().join(dir).join(name)))
        .sum()
}

/// Every `.rs` file in a directory, sorted, so the count does not depend on the
/// order the file system hands them back.
fn rust_files(dir: &str) -> Vec<PathBuf> {
    let mut found: Vec<PathBuf> = fs::read_dir(root().join(dir))
        .expect("the directory is in the repository")
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| path.extension().is_some_and(|ext| ext == "rs"))
        .collect();
    found.sort();
    found
}

#[test]
fn the_readme_line_counts_are_the_line_counts() {
    let text = readme();
    // Each row of the structure table names its files and claims their total.
    // Parsed from the README rather than listed here, so adding a row to the
    // table is enough to have it checked.
    let mut checked = 0;
    let mut wrong = Vec::new();
    for line in text.lines() {
        let cells: Vec<&str> = line.split('|').map(str::trim).collect();
        // | **Stage** | files | count | description |
        if cells.len() < 5 || !cells[1].starts_with("**") {
            continue;
        }
        let Ok(claimed) = cells[3].trim_matches('*').parse::<usize>() else {
            continue;
        };
        let names: Vec<&str> = cells[2].split(',').map(str::trim).collect();
        if !names.iter().all(|name| name.ends_with(".rs")) {
            continue;
        }
        let actual = lines_of("src", &names);
        checked += 1;
        if actual != claimed {
            wrong.push(format!(
                "  {} claims {claimed} lines, has {actual}",
                cells[2]
            ));
        }
    }

    assert!(
        checked >= 5,
        "only {checked} rows of the structure table were understood; \
         the table's shape changed and this test stopped reading it"
    );
    assert!(
        wrong.is_empty(),
        "the README's structure table is out of date:\n{}",
        wrong.join("\n")
    );
}

#[test]
fn the_readme_total_is_the_total() {
    let text = readme();
    let files = rust_files("src");
    let total: usize = files.iter().map(|path| lines_in(path)).sum();

    assert!(
        text.contains(&format!("**{} files**", files.len())),
        "the README does not say there are {} files in src/",
        files.len()
    );
    assert!(
        text.contains(&format!("**{total}**")),
        "the README does not give the total as {total} lines"
    );
}

#[test]
fn the_readme_playground_counts_are_right() {
    let text = readme();
    let rust: usize = rust_files("playground/src")
        .iter()
        .map(|path| lines_in(path))
        .sum();
    // The hand-written half. `pkg/` is generated by wasm-bindgen and is not
    // anybody's work to claim.
    let web: usize = ["index.html", "style.css", "main.js"]
        .iter()
        .map(|name| lines_in(&root().join("playground/web").join(name)))
        .sum();

    assert!(
        text.contains(&format!("{rust} lines of Rust")),
        "the README does not say the playground is {rust} lines of Rust"
    );
    assert!(
        text.contains(&format!("and {web} of hand-written")),
        "the README does not say the playground has {web} hand-written lines of \
         HTML, CSS, and JavaScript"
    );
}

#[test]
fn the_readme_badge_gives_the_number_of_tests() {
    // Counted by attribute rather than by running anything, because a test
    // cannot ask how many tests there are without counting itself in a way that
    // depends on which binary is running. `cargo test --workspace` reported the
    // same figure this counts when the check was written, and it will keep
    // agreeing as long as every test is an ordinary `#[test]`.
    let mut count = 0;
    for dir in ["src", "tests", "playground/src"] {
        for path in rust_files(dir) {
            count += fs::read_to_string(&path)
                .expect("the file is readable")
                .lines()
                .filter(|line| line.trim() == "#[test]")
                .count();
        }
    }

    let text = readme();
    assert!(
        text.contains(&format!("tests-{count}_passing")),
        "the README badge does not say {count} tests; \
         it is the count of `#[test]` functions in src/, tests/, and playground/src/"
    );
    assert!(
        text.contains(&format!("alt=\"{count} tests passing\"")),
        "the README badge's alt text does not say {count} tests"
    );
}
