#!/usr/bin/env bash
# Regenerate the builtin and keyword alternations inside the editor grammars,
# from BUILTIN_NAMES in src/builtins.rs and from the lexer's own keyword table
# plus RESERVED_WORDS in src/token.rs.
#
# That builtin array has moved in five consecutive releases, so a list of names
# typed by hand into a grammar is a list that is wrong within a month. This
# reads the one place that is always right, and `tests/specification.rs` already
# holds that place to the specification in both directions.
#
# The keyword alternation was typed by hand until version 2 doubled the number
# of keywords, which is exactly the moment a hand-maintained copy goes stale.
#
# Run it after adding a builtin or a keyword, and commit what it changes.

set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
grammar="$root/editors/vscode/syntaxes/miruscriptx.tmLanguage.json"

# Every quoted name between the opening bracket of BUILTIN_NAMES and its closing
# one. `sed -n` over that range keeps this from picking up a quoted string
# anywhere else in the file.
names="$(
  sed -n '/^pub const BUILTIN_NAMES/,/^];/p' "$root/src/builtins.rs" |
    grep -o '"[a-z_]*"' |
    tr -d '"'
)"

count="$(printf '%s\n' "$names" | wc -l | tr -d ' ')"

# Longest first. A regular expression alternation is tried left to right, so
# `in` before `index_of` would match the first two characters of `index_of` and
# colour the rest as ordinary text.
alternation="$(
  printf '%s\n' "$names" |
    awk '{ print length($0), $0 }' |
    sort -rn -k1,1 -k2,2 |
    cut -d' ' -f2- |
    paste -sd'|' -
)"

# The keywords, from the lexer's own table and from the reserved list.
#
# `true`, `false` and `nil` come out of the lexer's table with the rest and are
# dropped here: the grammar colours them as constants, which is what they are to
# a reader, and putting them in both scopes would colour whichever pattern ran
# first.
keywords="$(
  sed -n '/fn read_identifier/,/^    }$/p' "$root/src/lexer.rs" |
    grep -oE '"[a-z]+" => TokenKind::[A-Za-z]+' |
    sed 's/" =>.*//; s/^"//' |
    grep -vxE 'true|false|nil'
)"

reserved="$(
  sed -n '/^pub const RESERVED_WORDS/,/^];/p' "$root/src/token.rs" |
    grep -o '"[a-z_]*"' |
    tr -d '"'
)"

keyword_count="$(printf '%s\n%s\n' "$keywords" "$reserved" | wc -l | tr -d ' ')"

keyword_alternation="$(
  printf '%s\n%s\n' "$keywords" "$reserved" |
    awk '{ print length($0), $0 }' |
    sort -rn -k1,1 -k2,2 |
    cut -d' ' -f2- |
    paste -sd'|' -
)"

python3 - "$grammar" "$alternation" "$count" "$keyword_alternation" "$keyword_count" <<'PY'
import json
import re
import sys

path, alternation, count = sys.argv[1], sys.argv[2], int(sys.argv[3])
keyword_alternation, keyword_count = sys.argv[4], int(sys.argv[5])

with open(path) as handle:
    grammar = json.load(handle)

pattern = grammar["repository"]["builtin"]["patterns"][0]
# A negative lookbehind for the dot, not a lookahead for `(`. This matches
# `class_of` in playground/src/lib.rs, which colours a builtin wherever the
# name appears and not only where it is called: `map(xs, sort)` colours both.
# What it must not colour is a field, so `c.len` names a field of `c` while
# `len(c)` calls the builtin.
pattern["match"] = rf"(?<!\.)\b(?:{alternation})\b"
grammar["repository"]["builtin"]["comment"] = (
    f"The {count} builtins, longest first. Generated by scripts/build_grammar.sh "
    "from BUILTIN_NAMES in src/builtins.rs. Do not edit by hand."
)

keyword = grammar["repository"]["keyword"]["patterns"][0]
keyword["match"] = rf"\b(?:{keyword_alternation})\b"
grammar["repository"]["keyword"]["comment"] = (
    f"The {keyword_count} keywords, longest first. Generated by "
    "scripts/build_grammar.sh from the lexer's keyword table and RESERVED_WORDS "
    "in src/token.rs. Do not edit by hand."
)

with open(path, "w") as handle:
    json.dump(grammar, handle, indent=2)
    handle.write("\n")

print(f"Wrote {count} builtin names and {keyword_count} keywords into {path}")
PY
