#!/usr/bin/env bash
# Regenerate the builtin alternation inside the editor grammars from
# BUILTIN_NAMES in src/builtins.rs.
#
# That array has moved in five consecutive releases, so a list of builtin names
# typed by hand into a grammar is a list that is wrong within a month. This
# reads the one place that is always right, and `tests/specification.rs` already
# holds that place to the specification in both directions.
#
# Run it after adding a builtin, and commit what it changes.

set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
grammar="$root/editors/vscode/syntaxes/miruscriptx.tmLanguage.json"

# Every quoted name between the opening bracket of BUILTIN_NAMES and its closing
# one. `sed -n` over that range keeps this from picking up a quoted string
# anywhere else in the file.
names="$(
  sed -n '/^pub const BUILTIN_NAMES/,/^];/p' "$root/src/builtins.rs" |
    grep -o '"[a-z_]*"' |
    tr -d '"'
)"

count="$(printf '%s\n' "$names" | wc -l | tr -d ' ')"

# Longest first. A regular expression alternation is tried left to right, so
# `in` before `index_of` would match the first two characters of `index_of` and
# colour the rest as ordinary text.
alternation="$(
  printf '%s\n' "$names" |
    awk '{ print length($0), $0 }' |
    sort -rn -k1,1 -k2,2 |
    cut -d' ' -f2- |
    paste -sd'|' -
)"

python3 - "$grammar" "$alternation" "$count" <<'PY'
import json
import re
import sys

path, alternation, count = sys.argv[1], sys.argv[2], int(sys.argv[3])

with open(path) as handle:
    grammar = json.load(handle)

pattern = grammar["repository"]["builtin"]["patterns"][0]
# A negative lookbehind for the dot, not a lookahead for `(`. This matches
# `class_of` in playground/src/lib.rs, which colours a builtin wherever the
# name appears and not only where it is called: `map(xs, sort)` colours both.
# What it must not colour is a field, so `c.len` names a field of `c` while
# `len(c)` calls the builtin.
pattern["match"] = rf"(?<!\.)\b(?:{alternation})\b"
grammar["repository"]["builtin"]["comment"] = (
    f"The {count} builtins, longest first. Generated by scripts/build_grammar.sh "
    "from BUILTIN_NAMES in src/builtins.rs. Do not edit by hand."
)

with open(path, "w") as handle:
    json.dump(grammar, handle, indent=2)
    handle.write("\n")

print(f"Wrote {count} builtin names into {path}")
PY
